@startuml

'abstract class AposSdkProtocol {
'    StatusCode AposSdkRead(int32_t handle, BinPack *in_data, BinPack *out_data, int32_t timeout);
'    StatusCode AposSdkWrite(int32_t handle, BinPack *out_data, int32_t timeout);
'    StatusCode AposSdkSendEvent(int32_t handle, const char *event_id, BinPack *in_data);
'    StatusCode AposSdkSetEventSubscribe(int32_t handle, AposSdkEventCallback callback, const char **event_ids, uint32_t event_size);
'    StatusCode AposSdkService(int32_t handle, const char *event_id, BinPack *in_data, BinPack *out_data, int32_t timeout);
'}
'
'note top of AposSdkProtocol:  typedef void (*AposSdkEventCallback)(int32_t handle, const char *event_id, int32_t msg_id, BinPack *in_msg);
'
'abstract class BaseAposIotSdk {
'    AposSdkProtocol apos_sdk;
'}

participant Network
participant PropertyManager
participant APOS_SDK
participant Protocol_Interface
participant AppSweeper

autonumber
Network -> Network: 进程启动
APOS_SDK -> Protocol_Interface: 订阅数据更新主题
AppSweeper -> Protocol_Interface: 订阅数据更新主题

PropertyManager -> PropertyManager: 开启线程1，轮询配置文件数据状态
PropertyManager -> APOS_SDK: 订阅数据更新主题
APOS_SDK -> Protocol_Interface: 订阅数据更新主题
    loop 每5s
        PropertyManager -> APOS_SDK: 获取/userdata/config/configs.json、/tmp/run/last_record/clean_info.json
        PropertyManager <-- APOS_SDK: 结果
        PropertyManager -> PropertyManager: 对比是否变化
        alt 有变化
            PropertyManager -[#red]-> Network: 上报
            PropertyManager --> PropertyManager: 更新
        end

        alt IOT变更
            Network -> PropertyManager: 指令下发
            PropertyManager -> APOS_SDK: 指令下发
            APOS_SDK -> Protocol_Interface: 指令下发
            Protocol_Interface -> Protocol_Interface: 属性变更
            Protocol_Interface --> APOS_SDK: 属性变更
            APOS_SDK --> PropertyManager: 属性变更
            PropertyManager -[#red]-> Network: 立即上报
        else 应用层变更
            AppSweeper -> Protocol_Interface: 指令下发
            Protocol_Interface -> Protocol_Interface: 属性变更
            Protocol_Interface --> APOS_SDK: 属性变更
            APOS_SDK --> PropertyManager: 属性变更
            PropertyManager -[#red]-> Network: 立即上报
        end
    end
PropertyManager -> PropertyManager: 开启线程2，轮询内存数据状态
    loop 每300ms
        PropertyManager -> APOS_SDK: 获取SHM_GOODS_JSON、common_node_attr、task_manager_attr
        PropertyManager <-- APOS_SDK: 结果
        alt 有变化
            PropertyManager -[#red]-> Network: 上报
            PropertyManager --> PropertyManager: 更新
        end
    end
@enduml
